import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, Menu, X } from 'lucide-react'

const projects=[
{id:'01',short:'EMS',tone:'violet',type:'Full Stack Platform',title:'Smart Event Management System',description:'A secure event platform covering discovery, venues, bookings, attendees, PayHere payments, reminders and AI-assisted previews.',stack:['React','TypeScript','Redux','Spring Boot','MySQL','JWT'],url:'https://github.com/jayanidissanayake15/Smart_EMS'},
{id:'02',short:'SPMS',tone:'blue',type:'Cloud-native Backend',title:'Smart Parking Management System',description:'A multi-service parking platform with gateway routing, centralized configuration, service discovery and independent databases.',stack:['Java 17','Spring Cloud','Eureka','OpenFeign','H2'],url:'https://github.com/jayanidissanayake15/Micro_Service_Project'},
{id:'03',short:'HITHA',tone:'green',type:'Cross-platform Mobile',title:'Hitha Wellness App',description:'A calm mood, diary and wellness companion with goals, AI support, Firebase services and secure local storage.',stack:['React Native','Expo','TypeScript','Firebase'],url:'https://github.com/jayanidissanayake15/Mobile_Application'},
{id:'04',short:'QUEUE',tone:'orange',type:'REST API',title:'Smart Queue Management',description:'A layered backend for services, counters, automated queue tokens, customer history and queue operations.',stack:['Java 17','Spring Boot','JPA','MySQL'],url:'https://github.com/jayanidissanayake15/Smart-Queue-_Final_Project'},
{id:'05',short:'MERN',tone:'teal',type:'Education Platform',title:'Student Management System',description:'A full-stack academic platform with role-based access, assignments, notices, reports, AI assistance and real-time features.',stack:['MongoDB','Express','React','Node.js','Docker'],url:'https://github.com/jayanidissanayake15/Student_management_system_mern-main'},
{id:'06',short:'STAY',tone:'gold',type:'Desktop Application',title:'Holiday Home Management',description:'A layered management system designed to organize bookings, guests and day-to-day holiday-home operations.',stack:['Java','JavaFX','MySQL','Layered Architecture'],url:'https://github.com/jayanidissanayake15/Holiday-Home-Management-System-Layered'}]

const skills=[{label:'Frontend',value:['React · Next.js','React Native · TypeScript','Redux · Tailwind CSS']},{label:'Backend & Data',value:['Java · Spring Boot','Node.js · Express','MySQL · MongoDB']},{label:'Security & DevOps',value:['Spring Security · JWT','Git · Linux · Docker','Kubernetes · CI/CD']}]

function SectionHeading({number,eyebrow,line1,line2}){return <div className="section-heading reveal"><p>{number} / {eyebrow}</p><h2>{line1}<br/><em>{line2}</em></h2></div>}

export default function App(){
 const[menuOpen,setMenuOpen]=useState(false)
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[])
 const close=()=>setMenuOpen(false)
 return <><header className="site-header"><a className="brand" href="#home" onClick={close}>JD<span>.</span></a><nav className={menuOpen?'open':''} aria-label="Main navigation"><a href="#projects" onClick={close}>Projects</a><a href="#journey" onClick={close}>Journey</a><a href="#skills" onClick={close}>Skills</a><a href="#contact" onClick={close}>Contact</a></nav><a className="small-cta" href="https://github.com/jayanidissanayake15" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen?<X/>:<Menu/>}</button></header>
 <main><section className="hero section" id="home"><div className="hero-copy reveal"><p className="eyebrow"><i/> Available for a Full Stack Internship</p><h1>FULL STACK<br/><em>DEVELOPER</em></h1><p className="intro">I build secure, scalable web and mobile products—from thoughtful interfaces to dependable APIs.</p><div className="hero-actions"><a className="primary-btn" href="#projects">Explore my work <ArrowDownRight/></a><a className="text-link" href="https://github.com/jayanidissanayake15" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={18}/></a></div></div><aside className="identity-card reveal"><div className="monogram">JD</div><p className="status"><i/> Open to opportunities</p><h2>Jayani<br/>Dissanayake</h2><p>Full Stack Developer · Undergraduate</p></aside></section>
 <div className="marquee"><div>REACT • SPRING BOOT • TYPESCRIPT • NODE.JS • MONGODB • MYSQL • DOCKER • KUBERNETES •&nbsp; REACT • SPRING BOOT • TYPESCRIPT • NODE.JS • MONGODB • MYSQL • DOCKER • KUBERNETES •&nbsp;</div></div>
 <section className="section projects" id="projects"><SectionHeading number="01" eyebrow="Selected work" line1="PROJECTS THAT" line2="SOLVE PROBLEMS."/><div className="project-grid">{projects.map((p,i)=><a className={`project-card reveal ${i===0?'featured':''}`} href={p.url} target="_blank" rel="noreferrer" key={p.id}><div className="project-top"><span>{p.id}</span><span>View repository <ArrowUpRight size={14}/></span></div><div className={`project-art ${p.tone}`}><b>{p.short}</b><i/><i/></div><div className="project-copy"><p>{p.type}</p><h3>{p.title}</h3><div>{p.description}</div><ul>{p.stack.map(item=><li key={item}>{item}</li>)}</ul></div></a>)}</div></section>
 <section className="section journey" id="journey"><SectionHeading number="02" eyebrow="My journey" line1="LEARNING. BUILDING." line2="EVOLVING."/><div className="timeline reveal"><article><time>2024 — Present</time><div><h3>BSc (Hons) Computer Science</h3><p>University of Lincoln, Malaysia · Delivered through the Institute of Software Engineering, Sri Lanka</p></div><span>In progress</span></article><article><time>Current focus</time><div><h3>Full Stack Engineering</h3><p>Building complete applications across interface, API, security, database and deployment layers.</p></div><span>Internship ready</span></article><article><time>Growing next</time><div><h3>Cloud & DevOps</h3><p>Developing practical knowledge in Linux, Docker, Kubernetes, CI/CD and cloud deployment.</p></div><span>Continuous learning</span></article></div></section>
 <section className="section skills" id="skills"><SectionHeading number="03" eyebrow="Technical toolkit" line1="TOOLS I USE TO" line2="SHIP IDEAS."/><div className="skill-columns reveal">{skills.map((s,i)=><div key={s.label}><span>0{i+1}</span><p>{s.label}</p><h3>{s.value.map(x=><span key={x}>{x}<br/></span>)}</h3></div>)}</div></section>
 <section className="section contact" id="contact"><p className="eyebrow reveal"><i/> Have an opportunity or an idea?</p><h2 className="reveal">LET'S BUILD<br/><em>SOMETHING GREAT.</em></h2><a className="contact-link reveal" href="https://github.com/jayanidissanayake15" target="_blank" rel="noreferrer">Start a conversation on GitHub <ArrowUpRight/></a><footer className="reveal"><span>© {new Date().getFullYear()} Jayani Dissanayake</span><a href="#home">Back to top ↑</a></footer></section></main></>}
